###
# @name Register
POST {{url}}/register
Accept: application/json
Content-Type: application/json

{
        "nir": "875543548",
        "firstname": "Jean",
        "lastname": "DUPOND",
        "email": "jdupond@gmail.com",
        "password": "test",
        "birthday": "12-02-2001",
        "address_street": "rue des sycomores",
        "town": "94079",
        "sex": 1,
        "profile": null
}

###
# @name Login App
POST {{url}}/login_app
Accept: application/json
Content-Type: application/json

{
  "nir": "875543548",
  "password": "test"
}

###
# @name Login BO
POST {{url}}/login_bo
Accept: application/json
Content-Type: application/json

{
  "nir": "875543548",
  "password": "test"
}

###
# @name Login Stats
POST {{url}}/login_stats
Accept: application/json
Content-Type: application/json

{
  "nir": "875543548",
  "password": "test"
}

