###
# @name Get all manifestation
GET http://localhost:3000/manifestation?includeAborted=true
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NDk1MTMwMDQsImV4cCI6MTY0OTU5OTQwNH0.n4ERguJqgu6PAwrpRWt2MguIE7T57HL0YlKEIYpNwX0

###
# @name Get all manifestation (without aborted)
GET http://localhost:3000/manifestation
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NDk1MTMwMDQsImV4cCI6MTY0OTU5OTQwNH0.n4ERguJqgu6PAwrpRWt2MguIE7T57HL0YlKEIYpNwX0

###
# @name Get all manifestation (mine)
GET http://localhost:3000/manifestation?mine=true
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NDk1MTMwMDQsImV4cCI6MTY0OTU5OTQwNH0.n4ERguJqgu6PAwrpRWt2MguIE7T57HL0YlKEIYpNwX0

###
# @name Aborted manifestation
PATCH http://localhost:3000/manifestation/aborted
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NDkzMjEzOTUsImV4cCI6MTY0OTQwNzc5NX0.j8gLqLq3wReClks61WpwnNzvGccOJNxxIVy0sBPizmI
Content-Type: application/json

{
  "id": 7,
  "reason": "Il pleut"
}

###
# @name Participate to manifestation
POST http://localhost:3000/manifestation/participate/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NDk1MTMwMDQsImV4cCI6MTY0OTU5OTQwNH0.n4ERguJqgu6PAwrpRWt2MguIE7T57HL0YlKEIYpNwX0
Content-Type: application/json

###
# @name Add new option to manifestation
POST http://localhost:3000/manifestation/option
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NDk1MjE0MjUsImV4cCI6MTY0OTYwNzgyNX0.lKBuuCJm0vreUQ25jfVAbbRMuMoNBAk5lHqRiO-DdIM
Content-Type: application/json

{
  "name": "Hauts-parleurs",
  "id_manifestation": 2
}

###
# @name Get options from manifestation
GET http://localhost:3000/manifestation/option/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NTAyOTMxMDMsImV4cCI6MTY1MDM3OTUwM30.b-Tj2xcERKz17eMYW8ljS1hKNNKhWO39jK2YLp9HkzI
Content-Type: application/json

###
# @name Delete options of manifestation
DELETE http://localhost:3000/manifestation/option/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NDk1MjE0MjUsImV4cCI6MTY0OTYwNzgyNX0.lKBuuCJm0vreUQ25jfVAbbRMuMoNBAk5lHqRiO-DdIM
Content-Type: application/json

###
# @name Add new step to manifestation
POST http://localhost:3000/manifestation/step
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NTAyOTMxMDMsImV4cCI6MTY1MDM3OTUwM30.b-Tj2xcERKz17eMYW8ljS1hKNNKhWO39jK2YLp9HkzI
Content-Type: application/json

{
  "address_street": "28 rue de Noisy",
  "date_arrived": "2022-05-20",
  "id_manifestation": 3,
  "id_step_type": 1,
  "town_code_insee": "94079"
}

###
# @name Get steps from manifestation
GET http://localhost:3000/manifestation/step/3
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NTAyOTMxMDMsImV4cCI6MTY1MDM3OTUwM30.b-Tj2xcERKz17eMYW8ljS1hKNNKhWO39jK2YLp9HkzI
Content-Type: application/json

###
# @name Delete step of manifestation
DELETE http://localhost:3000/manifestation/step/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NTAyOTMxMDMsImV4cCI6MTY1MDM3OTUwM30.b-Tj2xcERKz17eMYW8ljS1hKNNKhWO39jK2YLp9HkzI
Content-Type: application/json
