###
# @name Get all meeting
GET {{url}}/meeting?includeAborted=true
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
# @name Get all meeting (without aborted)
GET {{url}}/meeting
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
# @name Get all meeting (mine)
GET {{url}}/meeting?mine=true
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
# @name Add new meeting
POST {{url}}/meeting
Accept: application/json
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "name": "Meeting annuel Horizons",
  "object": "Meeting annuel",
  "date_start": "2022-07-28",
  "nb_time": 2.20,
  "id_political_party": 32,
  "price_excl": 0,
  "vta_rate": 0,
  "street_address": "5 rue de Tahure",
  "town_code_insee": "76351"
}
