###
# @name Add thread
POST {{url}}/thread
Accept: application/json
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "name": "Test",
  "id_political_party": 3
}

###
# @name Update thread
PUT {{url}}/thread
Accept: application/json
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "id": 2,
  "name": "THE_TEST",
  "id_political_party": 3
}

###
# @name Change main thread
PATCH {{url}}/thread/2/main/3
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
# @name Delete thread
DELETE {{url}}/thread/2
Accept: application/json
Authorization: Bearer {{jwt_token}}
