###
# @name Add new vote
POST {{url}}/vote
Accept: application/json
Authorization: Bearer {{jwt_token}}
Content-Type: application/json

{
  "name": "test",
  "date_start": "2022-02-02",
  "date_end": "2022-02-02",
  "num_round": 2,
  "id_type_vote": 1,
  "nb_voter": 20000
}
