###
# @name Add new vote
POST http://localhost:3000/vote
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaXIiOiI4NzU1NDM1NDgiLCJpYXQiOjE2NTA2OTg3MDUsImV4cCI6MTY1MDc4NTEwNX0.B9HzTJ3Dd3YOzh-qZAGK6NuKhp02PGnp5kyK6JRviUE
Content-Type: application/json

{
  "name": "test",
  "date_start": "2022-02-02",
  "date_end": "2022-02-02",
  "num_round": 2,
  "id_type_vote": 1,
  "nb_voter": 20000
}
